### ISSUE TITLE
[Hyejin] design record section

### ISSUE THREAD

**Issue by hyejinU** [hyejinU/today-exchange#4]
외화보유량을 기록하는 부분을 Bootstrap의 카드 레이아웃을 이용해 디자인했습니다.
Bootstrap 커멘드를 이용해 클릭 이벤트를 다루려고 했으나 적용이 안 되어서 자바스크립트를 이용해 수정할 예정입니다.

수정할 사항
- [ ] script.js 에 외화 tab을 클릭하면 tab content가 바뀌도록

**Comment by cho-to** [comment]
#2 에 대한 enhancement인 것 같습니다
