### ISSUE TITLE
[Hyejin] Record section re-design

### ISSUE THREAD

**Issue by hyejinU** [hyejinU/today-exchange#7]
외화 보유량 기록 부분 디자인을 수정했습니다.

카드 탭을 이용해 창이 바뀌는 형식이 아닌, 외화 종류마다 테이블을 만들었습니다.
사용자는 외화 금액과 날짜를 입력하면, 테이블 하단에 외화의 총합을 계산합니다.

**Comment by cho-to** [comment]
넵 관련사항은 #2를 참조해주세요!
