### ISSUE TITLE
[Hyejin] record section event handling

### ISSUE THREAD

**Issue by hyejinU** [hyejinU/today-exchange#8]
script.js 파일에 외화 보유량 기록 부분을 동적할당하는 기능을 만들었습니다.
외화 종류, 금액, 날짜를 입력해 버튼을 누르면 아래 테이블에 추가됩니다.
clear 버튼을 누르면 local storage가 비워져, 새로고침 했을 때 갱신됩니다.

**Comment by cho-to** [comment]
확인했습니다! 이 이슈 관련 초기사항은 #2 를 확인해주세요.
